include_directories(include)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
include_directories(${CMAKE_SOURCE_DIR}/third_party)
include_directories(${CMAKE_SOURCE_DIR}/src/include)
include_directories(${CMAKE_SOURCE_DIR}/src/utils/include)
include_directories(${DuckDB_SOURCE_DIR}/third_party)
include_directories(${DuckDB_SOURCE_DIR}/test/include)

set(CATCHFS_UNITTEST_OBJECTS
    main.cpp
    test_base_cache_filesystem_from_unit.cpp
    test_cache_exclusion_manager.cpp
    test_cache_filesystem_from_unit.cpp
    test_cache_filesystem_with_mock.cpp
    test_cache_stats_collection_from_unit.cpp
    test_chunk_utils.cpp
    test_clear_cache_on_delete.cpp
    test_clear_cache_on_write.cpp
    test_copiable_value_lru_cache.cpp
    test_connection_cleanup.cpp
    test_constants.cpp
    test_counter.cpp
    test_data_cache_remap.cpp
    test_disk_cache_filesystem_from_unit.cpp
    test_disk_cache_util.cpp
    test_disk_cache_validation_from_unit.cpp
    test_disk_cache_with_multi_directories_from_unit.cpp
    test_exclusive_lru_cache.cpp
    test_exclusive_multi_lru_cache.cpp
    test_filesystem_config_from_unit.cpp
    test_filesystem_utils_from_unit.cpp
    test_histogram.cpp
    test_in_memory_cache_filesystem_from_unit.cpp
    test_io_operation_latency.cpp
    test_latency_guard.cpp
    test_large_file_disk_reader_from_unit.cpp
    test_large_file_inmem_reader_from_unit.cpp
    test_max_fanout_subrequest.cpp
    test_multi_duckdb_instance_from_unit.cpp
    test_no_destructor.cpp
    test_noop_cache_reader_from_unit.cpp
    test_object_cache_data_storage.cpp
    test_optional.cpp
    test_oversized_cache_filepath.cpp
    test_page_aligned_data_chunk.cpp
    test_read_exception_propagation.cpp
    test_remove_files_batch.cpp
    test_scoped_directory.cpp
    test_set_extension_config_from_unit.cpp
    test_shared_value_lru_cache.cpp
    test_size_literals.cpp
    test_stats_cache.cpp
    test_thread_pool.cpp
    test_url_utils.cpp
    test_utils.cpp
    test_w_tinylfu_cache.cpp)

add_executable(unittest_cache_httpfs ${CATCHFS_UNITTEST_OBJECTS})

if(NOT WIN32
   AND NOT SUN
   AND NOT ZOS)
  target_link_libraries(
    unittest_cache_httpfs test_helpers duckdb ${EXTENSION_NAME}
    ${OPENSSL_LIBRARIES} ${CURL_LIBRARIES})
else()
  target_link_libraries(unittest_cache_httpfs test_helpers duckdb_static
                        ${OPENSSL_LIBRARIES} ${CURL_LIBRARIES})
  link_extension_libraries(unittest_cache_httpfs "")
endif()

if(MINGW OR WIN32)
  target_link_libraries(unittest_cache_httpfs crypt32)
endif()
